name: Auto Pull Request

on:
  push:
    branches:
      - "feature/*"

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Verificar se já existe um PR aberto
        id: check-pr
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          PR_EXISTS=$(gh pr list --base master --head "$BRANCH_NAME" --state open --json number --jq 'length' || echo 0)
          echo "EXISTING_PR=$PR_EXISTS" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB }}

      - name: Criar Pull Request (se não existir)
        if: env.EXISTING_PR == '0'
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          gh pr create \
            --base master \
            --head "$BRANCH_NAME" \
            --title "Merge $BRANCH_NAME into master" \
            --body "Pull request automático para unir $BRANCH_NAME na master 🚀"
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB }}
